/*
 * This file was generated by node-ffi-packager v1.0.0.
 * https://github.com/node-ffi-packager
 *
 * Library: libuvc
 * Conan.io recipe reference: libuvc/0.0.6
 * Conan.io remote: conan-center
 * Conan.io package id: 34cb7de83f8a038fdf6a04644ea265f82fef1be9
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libuvcLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
