/*
 * This file was generated by @ffi-packager/ffi-packager v2.0.0.
 * https://github.com/node-ffi-packager
 *
 * Library: libuvc
 * Conan.io recipe reference: libuvc/0.0.6
 * Conan.io remote: conan-center
 * Conan.io package id: fd3a12e9fb10dddd2d7131da2f6920cb125f879d
 */

const { loadLibrary } = require("../loader");

const input = require("./index.json");

module.exports = {
  // NOTE: named wrapper function with library name prefix to make it easier to spot in a stack trace.
  // NOTE: assumes that the library name is in a suitable format.
  load: async function libuvcLibraryLoader() {
    return loadLibrary(__dirname, input);
  },
};
